---
# This is mainly for capistrano later since sudo is no longer available in v3
- name: create sudoers file
  sudo: yes
  template: src=sudoers.j2 dest=/etc/sudoers.d/{{ user }}_appservers validate='visudo -cf %s' owner=root group=root mode=0440

- include: unicorn.yml
