---
- name: update deploy user 
  sudo: yes
  user: name={{user}} state=present generate_ssh_key=yes ssh_key_bits=2048

- name: copy local ssh keys to deploy user
  sudo: yes
  copy: src={{local_ssh_key}} dest=/home/{{user}}/.ssh/authorized_keys owner={{user}}

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  sudo: yes
  notify: restart ssh

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  sudo: yes
  notify: restart ssh

- name: update apt-get 
  sudo: yes
  apt: update_cache=yes upgrade=safe #force=True

- name: install common packages
  sudo: yes
  apt: pkg={{item}} state=present
  with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - git
    - git-core
    - libtool
    - libreadline6
    - libreadline6-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt1-dev
    - libc6-dev
    - nodejs
    - openssl
    - pkg-config
    - python-software-properties
    - zlib1g
    - zlib1g-dev
    - vim

- include: iptables.yml 
- include: fail2ban.yml 
- include: monit.yml 
